# Generated by Django 6.0.2 on 2026-03-08 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('payout_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('next_payout', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('auto_reinvest', models.BooleanField(default=False)),
                ('market_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dividend_proj.dividenddata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
