# Generated by Django 6.0.2 on 2026-03-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividend_proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividenddata',
            options={'verbose_name_plural': 'Dividend Data'},
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='shares',
            new_name='shares_amnt',
        ),
    ]
