# Generated by Django 6.0.2 on 2026-03-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividend_proj', '0002_alter_dividenddata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividenddata',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
